JaTrMd/objects/Api_Key__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Api Key</label>
    <pluralLabel>Api Keys</pluralLabel>
</CustomObject>

JaTrMd/objects/Dump__c.object
<CustomObject>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Dump</label>
    <nameField>
        <label>Dump Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dumps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JaTrMd/objects/Position__c.object
<CustomObject>
    <description>The position for which a company is trying to hire an applicant</description>
    <fields>
        <fullName>Job_Location__c</fullName>
        <description>The location of the jobsite</description>
        <inlineHelpText>The location of the jobsite</inlineHelpText>
        <label>Job Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-site</fullName>
                </value>
                <value>
                    <fullName>Remote</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position_Description__c</fullName>
        <description>The detailed description of the position</description>
        <inlineHelpText>The detailed description of the position</inlineHelpText>
        <label>Position Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Position_Link__c</fullName>
        <description>The URL from which the job posting came, if it came from the Web</description>
        <inlineHelpText>The URL from which the job posting came, if it came from the Web</inlineHelpText>
        <label>Position Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The title of the position</description>
        <inlineHelpText>The title of the position</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>PSN-{00000}</displayFormat>
        <label>Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>The value of the salary allowed for the position</description>
    <inlineHelpText>The value of the salary allowed for the position</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>The source of the position announcement</description>
    <inlineHelpText>The source of the position announcement</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Time_Type__c.field-meta.xml
<CustomField>
    <fullName>Time_Type__c</fullName>
    <description>The type of employee, in terms of regular employee or contractor</description>
    <inlineHelpText>The type of employee, in terms of regular employee or contractor</inlineHelpText>
    <label>Employee Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full-time Salaried</fullName>
                <default>true</default>
                <label>Full-time Salaried</label>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Rest_Classes/JoobleCallout.cls
/**
 * @description       :
 * @author            : admillican08@gmail.com
 * @group             :
 * @last modified on  : 09-23-2024
 * @last modified by  : admillican08@gmail.com
 **/
public with sharing class JoobleCallout {
  @future(callout=true)
  public static void getJoobleJobListing() {
    String apiKey = [
      SELECT MasterLabel, Value__c
      FROM Api_Key__mdt
      WHERE MasterLabel = 'Jooble'
      LIMIT 1
    ]
    .Value__c;
    String keywordStr = '{ keywords: \'Salesforce\', location: \'United States\'}';
    // Create HTTP request to send.
    HttpRequest request = new HttpRequest();
    // Set the endpoint URL. Use direct URL or for best practices use Named Credential.
    request.setEndpoint('callout:Jooble' + '/' + apiKey);
    request.setHeader('Content-type', 'application/json');
    // Set the HTTP method to POST.
    request.setMethod('POST');
    request.setBody(keyWordStr);
    // Send the HTTP request and get the response.
    Http http = new Http();
    HttpResponse response = http.send(request);
    // If the HTTP response code is successful

    if (response.getStatusCode() == 200) {
      String jsonStr = response.getBody();
      jsonStr = removeExtraneous(jsonStr);
      // newDump = new Dump__c(Text__c = jsonStr);
      //insert newDump;
      JSONParser parser = JSON.createParser(jsonStr);
      List<Position__c> joobleJobLst = new List<Position__c>();
      parser.nextToken();
      parser.nextToken();
      while (parser.nextToken() != null) {
        Position__c newPosn = new Position__c();

        joobleJobLst.add(newPosn);
      }
      System.debug('**Size of Jooble Job List is ' + joobleJobLst.size());
    }
  }

  @testVisible
  private static String removeExtraneous(String input) {
    input = input.replaceAll('\\\\[a-z]', '');
    input = input.replaceAll('~', '');
    input = input.replaceAll('&nbsp;', '');
    input = input.replaceAll('\\?\\?', '');
    input = input.replaceAll('</*[a-z]>', '');
    return input;
  }

  @testVisible
  private static Position__c createPosition(
    JsonParser parser,
    Position__c posn
  ) {
    if (parser.getCurrentToken() == JSONToken.FIELD_NAME) {
      switch on parser.getText() {
        when 'title' {
          parser.nextValue();
          posn.Title__c = parser.getText();
        }
        when 'location' {
          parser.nextValue();
          posn.Job_Location__c = parser.getText();
        }
        when 'snippet' {
          parser.nextValue();
          posn.Position_Description__c = parser.getText();
        }
        when 'salary' {
          parser.nextValue();
          posn.Salary__c = Decimal.valueOf(parser.getText());
        }
        when 'source' {
          parser.nextValue();
          posn.Source__c = parser.getText();
        }
        when 'type' {
          parser.nextValue();
          posn.Time_Type__c = parser.getText();
        }
        when 'link' {
          parser.nextValue();
          posn.Position_Link__c = parser.getText();
        }
        when 'company' {
          parser.nextValue();
          posn.company = parser.getText();
        }
        when 'updated' {
          parser.nextValue();
          posn.updated = parser.getText();
        }
        when 'id' {
          parser.nextValue();
          posn.id = parser.getText();
          System.debug('**New job: ' + posn);
        }
      }
    }
    return posn;
  }
}