JaTrMd/objects/Exception_Log__e.object
<CustomObject>
    <description>Platform event associated with exception recording. Captures information about exceptions even before they are rolled back, if applicable. W-014715</description>
    <fields>
        <fullName>Exception_Details__c</fullName>
        <description>The information regarding the exception itself. W-014715</description>
        <label>Exception Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Obj_Record_Id__c</fullName>
        <description>The unique record ID of the object record on which the exception was thrown, or, for batch jobs, the first record of the batch in which the exception was thrown. W-014715</description>
        <label>Obj Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>The object tyoe upon which the exception was thrown. W-014715</description>
        <label>Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <description>The class or flow being executed when the exception was thrown. W-014715</description>
        <label>Operation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>The particular process being executed when the exception was thrown. W-014715</description>
        <inlineHelpText>The particular process being executed when the exception was thrown</inlineHelpText>
        <label>Process</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_User_Id__c</fullName>
        <description>The Id of the user who was performing the operation when the exception was thrown. W-014075</description>
        <label>Running User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <pluralLabel>Exception Logs</pluralLabel>
</CustomObject>

force-app/main/default/classes/Utility_Classes/Util_ExceptionUtil.cls
/**
 * @description       :
 * @author            : admillican08@gmail.com
 * @group             :
 * @last modified on  : 09-10-2024
 * @last modified by  : admillican08@gmail.com
 **/

public without sharing class Util_ExceptionUtil {
  public class CustomException extends Exception {
  }

  @InvocableMethod(
    label='Invoke ExceptionUtil'
    description='throws new Custom Exception'
  )
  public static void throwCustomException(List<String> exMessage) {
    String msg = exMessage[0];
    if (!msg.startsWith('***ERROR: ') && !msg.startsWith('**ERROR: ')) {
      msg = '**ERROR: ' + exMessage[0];
    } else {
      msg = exMessage[0];
    }
    throw new CustomException(msg);
  }

  // publish an Exception platform event. This allows us
  // to capture Exception information even if the
  // Exception is rolled back

  public static void publishException(
    String objName,
    String procName,
    String opName,
    String recId,
    String excDetails
  ) {
    //Create platform event and assign
    Exception_Log__e pe = new Exception_Log__e();
    pe.Object__c = objName;
    pe.Process__c = procName;
    pe.Operation__c = opName;
    pe.Exception_Details__c = excDetails;
    pe.Obj_Record_Id__c = recId;
    pe.Running_User_Id__c = UserInfo.getUserId();
    EventBus.publish(pe);
    throwCustomException(new List<String>{ excDetails });
  }

  // publish multiple Platform Events. This allows us
  // to capture information aobut a series of Exceptions
  // thrown even if they are rolled back

  public static void publishException(
    String objName,
    String procName,
    String opName,
    List<Database.SaveResult> saveResLst
  ) {
    Exception_Log__e pe;
    for (Database.SaveResult res : saveResLst) {
      if (!res.isSuccess()) {
        // for every unsuccessful save, publish
        // an Exception Log event
        pe = new Exception_Log__e();
        pe.Object__c = objName;
        pe.Process__c = procName;
        pe.Operation__c = opName;
        for (Database.Error err : res.getErrors()) {
          String excDetail =
            err.getStatusCode() +
            ':' +
            err.getMessage() +
            '; ' +
            new dmlException().getStackTraceString();
          String recId = res.getId();
          Util_ExceptionUtil.publishException(
            objName,
            procName,
            opName,
            recId,
            excDetail
          );
        }
      }
    }
  }
}