JaTrMd/objects/Job_Application__c.object
<CustomObject>
    <description>Custom object for tracking job applications</description>
    <fields>
        <fullName>Notes__c</fullName>
        <description>The applicant&apos;s notes on the job application</description>
        <inlineHelpText>The applicant&apos;s notes on the job application</inlineHelpText>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job App Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JaTrMd/objects/Job_Application_Note__c.object
<CustomObject>
    <description>For holding Notes entries for Job Applications</description>
    <fields>
        <fullName>Entry_Date_Time__c</fullName>
        <description>The date and time on which the entry was made</description>
        <inlineHelpText>The date and time on which the entry was made</inlineHelpText>
        <label>Entry Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Entry__c</fullName>
        <description>The note entry</description>
        <inlineHelpText>The note entry</inlineHelpText>
        <label>Entry</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Job_Application__c</fullName>
        <description>The Job Application record to which this note belongs</description>
        <inlineHelpText>The Job Application record to which this note belongs</inlineHelpText>
        <label>Job Application</label>
        <referenceTo>Job_Application__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>JA_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application Note</label>
    <nameField>
        <label>JA Note</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Application Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Trigger_Classes/JobApplicationTriggerMethods.cls
/**
 * @description       :
 * @author            : admillican08@gmail.com
 * @group             :
 * @last modified on  : 09-11-2024
 * @last modified by  : admillican08@gmail.com
 **/
public with sharing class JobApplicationTriggerMethods {
  public static final String OBJ_NAME = 'Job_Application__c';
  public static String callingMethod = 'createJobApplicationNote';
  public Job_Application_Note__c createJobApplicationNote(
    String noteTxt,
    String jobAppId
  ) {
    Job_Application_Note__c newNote = new Job_Application_Note__c(
      Job_Application__c = jobAppId,
      Entry__c = noteTxt,
      Entry_Date_Time__c = System.now()
    );
    return newNote;
  }

  public String createJobApplicationNotes(
    Map<Id, Job_Application__c> oldJobAppLst,
    Map<Id, Job_Application__c> newJobAppLst
  ) {
    final String MTHD_NAME = 'createJobApplicationNotes';
    List<Job_Application_Note__c> jobAppNotesLst = new List<Job_Application_Note__c>();
    for (Job_Application__c newJobApp : newJobAppLst.values()) {
      Job_Application__c oldJobApp = oldJobAppLst.get(newJobApp.Id);
      if (
        newJobApp.Notes__c != oldJobApp.Notes__c &&
        !String.isBlank(newJobApp.Notes__c)
      ) {
        jobAppNotesLst.add(
          this.createJobApplicationNote(newJobApp.Notes__c, newJobApp.Id)
        );
      }
    }
    return Util_Insert.insertList(
      'Job_Application_Note__c',
      jobAppNotesLst,
      MTHD_NAME
    );
  }
}