JaTrMd/objects/Job_Application__c.object
<CustomObject>
    <description>Custom object for tracking job applications</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The company to which the position being applied for belongs</description>
        <inlineHelpText>The company to which the position being applied for belongs</inlineHelpText>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Description__c</fullName>
        <description>The detailed job description, copied from the position description but allows for editing and additions.</description>
        <inlineHelpText>The detailed job description, copied from the position description but allows for editing and additions.</inlineHelpText>
        <label>Job Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <description>The location of the position</description>
        <formula>TEXT(Position__r.Job_Location__c)</formula>
        <inlineHelpText>The location of the position</inlineHelpText>
        <label>Job Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>The position for which the job application is being submitted</description>
        <inlineHelpText>The position for which the job application is being submitted</inlineHelpText>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job App Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Position_Reported_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>Position_Reported_Last_Updated__c</fullName>
    <description>The date and time on which the position was last updated by the system, site, or board on which it was posted.</description>
    <inlineHelpText>The date and time on which the position was last updated by the system, site, or board on which it was posted.</inlineHelpText>
    <label>Position Reported Last Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>The applicant&apos;s desired salary for the position</description>
    <inlineHelpText>The applicant&apos;s desired salary for the position</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

JaTrMd/objects/Position__c.object
<CustomObject>
    <description>The position for which a company is trying to hire an applicant</description>
    <fields>
        <fullName>Company__c</fullName>
        <description>The company for which the position is open</description>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <description>The location of the jobsite</description>
        <inlineHelpText>The location of the jobsite</inlineHelpText>
        <label>Job Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-site</fullName>
                </value>
                <value>
                    <fullName>Remote</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position_Description__c</fullName>
        <description>The detailed description of the position</description>
        <inlineHelpText>The detailed description of the position</inlineHelpText>
        <label>Position Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Position_Link__c</fullName>
        <description>The URL from which the job posting came, if it came from the Web</description>
        <inlineHelpText>The URL from which the job posting came, if it came from the Web</inlineHelpText>
        <label>Position Link</label>
        <type>Url</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>PSN-{00000}</displayFormat>
        <label>Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Reported_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>Reported_Last_Updated__c</fullName>
    <description>The reported last updated date and time of the position (as opposed to the Salesforce audit field Last Modified Date)</description>
    <inlineHelpText>The reported last updated date and time of the position (as opposed to the Salesforce audit field Last Modified Date)</inlineHelpText>
    <label>Reported Last Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>The value of the salary allowed for the position</description>
    <inlineHelpText>The value of the salary allowed for the position</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Batch_Classes/JobApplicationCreatorBatch.cls
/**
 * @description       :
 * @author            : admillican08@gmail.com
 * @group             :
 * @last modified on  : 09-25-2024
 * @last modified by  : admillican08@gmail.com
 **/
public with sharing class JobApplicationCreatorBatch implements Database.Batchable<sObject> {
  public static final String OBJ_NAME = 'Job Application';
  public static final String CLS_NAME = 'JobApplicationCreatorBatch';

  public Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      'SELECT Id, Company__c, Job_Location__c, Position_Description__c, Position_Link__c, Salary__c, Reported_Last_Updated__c, (SELECT Id, Position__c, Position_Reported_Last_Updated__c FROM Job_Applications__r) FROM Position__c WHERE (CreatedDate = TODAY OR LastModifiedDate = TODAY) WITH USER_MODE'
    );
  }

  public void execute(Database.BatchableContext bc, List<Position__c> scope) {
    final String MTD_NAME = 'execute';
    for (Position__c posn : scope) {
      List<Job_Application__c> jobAppLst = new List<Job_Application__c>();
      if (posn.Job_Applications__r.size() == 0) {
        Job_Application__c jApp = new Job_Application__c();
        jApp.Position__c = posn.Id;
        jApp.Company__c = posn.Company__c;
        jApp.Job_Description__c = posn.Position_Description__c.replace(
          '\\.\\.\\.',
          ''
        );
        jApp.Salary__c = posn.Salary__c;
        jApp.Position_Reported_Last_Updated__c = posn.Reported_Last_Updated__c;
        jobAppLst.add(jApp);
      } else {
        for (Job_Application__c jobApp : posn.Job_Applications__r) {
          if (
            posn.Reported_Last_Updated__c <
            jobApp.Position_Reported_Last_Updated__c
          ) {
            jobApp.Company__c = posn.Company__c;
            jobApp.Job_Description__c = posn.Position_Description__c.replace(
              '\\.\\.\\.',
              ''
            );
            jobApp.Salary__c = posn.Salary__c;
            jobApp.Position_Reported_Last_Updated__c = posn.Reported_Last_Updated__c;
            jobAppLst.add(jobApp);
          }
        }
      }
      System.debug(
        Util_Upsert.upsertList(
          OBJ_NAME,
          jobAppLst,
          MTD_NAME + ' of ' + CLS_NAME
        )
      );
    }
  }

  public void finish(Database.BatchableContext bc) {
  }
}