JaTrMd/objects/Job_Application__c.object
<CustomObject>
    <description>Custom object for tracking job applications</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The company to which the position being applied for belongs</description>
        <inlineHelpText>The company to which the position being applied for belongs</inlineHelpText>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Description__c</fullName>
        <description>The detailed job description, copied from the position description but allows for editing and additions.</description>
        <inlineHelpText>The detailed job description, copied from the position description but allows for editing and additions.</inlineHelpText>
        <label>Job Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Position_Title__c</fullName>
        <description>The title of the position for which the applicant is applying</description>
        <formula>Position__r.Title__c</formula>
        <inlineHelpText>The title of the position for which the applicant is applying</inlineHelpText>
        <label>Position Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>The position for which the job application is being submitted</description>
        <inlineHelpText>The position for which the job application is being submitted</inlineHelpText>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job App Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Geographic_Job_Location__c.field-meta.xml
<CustomField>
    <fullName>Geographic_Job_Location__c</fullName>
    <description>The geographic location of the jobsite, reflected from the position</description>
    <formula>Position__r.Geographic_Job_Location__c</formula>
    <inlineHelpText>The geographic location of the jobsite, reflected from the position</inlineHelpText>
    <label>Geographic Job Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/How_Paid__c.field-meta.xml
<CustomField>
    <fullName>How_Paid__c</fullName>
    <description>How the employee for the position is to be paid</description>
    <inlineHelpText>How the employee for the position is to be paid</inlineHelpText>
    <label>How Paid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>How_Paid</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Reported_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>Position_Reported_Last_Updated__c</fullName>
    <description>The date and time on which the position was last updated by the system, site, or board on which it was posted.</description>
    <inlineHelpText>The date and time on which the position was last updated by the system, site, or board on which it was posted.</inlineHelpText>
    <label>Position Reported Last Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>The applicant&apos;s desired salary for the position</description>
    <inlineHelpText>The applicant&apos;s desired salary for the position</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

JaTrMd/objects/Position__c.object
<CustomObject>
    <description>The position for which a company is trying to hire an applicant</description>
    <fields>
        <fullName>Company__c</fullName>
        <description>The company for which the position is open</description>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position_Description__c</fullName>
        <description>The detailed description of the position</description>
        <inlineHelpText>The detailed description of the position</inlineHelpText>
        <label>Position Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Position_Link__c</fullName>
        <description>The URL from which the job posting came, if it came from the Web</description>
        <inlineHelpText>The URL from which the job posting came, if it came from the Web</inlineHelpText>
        <label>Position Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The title of the position</description>
        <inlineHelpText>The title of the position</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>PSN-{00000}</displayFormat>
        <label>Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Geographic_Job_Location__c.field-meta.xml
<CustomField>
    <fullName>Geographic_Job_Location__c</fullName>
    <description>The geographic location where the jobsite is located</description>
    <inlineHelpText>The geographic location where the jobsite is located</inlineHelpText>
    <label>Geographic Job Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/How_Paid__c.field-meta.xml
<CustomField>
    <fullName>How_Paid__c</fullName>
    <description>How the person with this position will be paid</description>
    <inlineHelpText>How the person with this position will be paid</inlineHelpText>
    <label>How Paid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>How_Paid</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Reported_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>Reported_Last_Updated__c</fullName>
    <description>The reported last updated date and time of the position (as opposed to the Salesforce audit field Last Modified Date)</description>
    <inlineHelpText>The reported last updated date and time of the position (as opposed to the Salesforce audit field Last Modified Date)</inlineHelpText>
    <label>Reported Last Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>The value of the salary allowed for the position</description>
    <inlineHelpText>The value of the salary allowed for the position</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Batch_Sched_Classes/JobApplicationCreatorBatchTest.cls
/**
 * @description       :
 * @author            : admillican08@gmail.com
 * @group             :
 * @last modified on  : 10-17-2024
 * @last modified by  : admillican08@gmail.com
 **/
@isTest
private class JobApplicationCreatorBatchTest {
  @testSetup
  static void makeData() {
    // Create a test account using Util_TestDataFactory
    List<Account> newAcctLst = Util_TestDataFactory.createTestAccounts(1, true);
    Account testAccount = newAcctLst[0];

    // Create sample Position records and associate with the account
    Position__c pos1 = new Position__c(
      Company__c = testAccount.Id, // Reference to the account
      Geographic_Job_Location__c = 'Hilo, HI',
      How_Paid__c = 'Hourly',
      Title__c = 'Salesforce Developer',
      Position_Description__c = 'Really exciting developer job in paradise.',
      Position_Link__c = 'https://companyA.com/jobs/1',
      Salary__c = 100000,
      Reported_Last_Updated__c = System.now()
    );
    insert pos1;

    Position__c pos2 = new Position__c(
      Company__c = testAccount.Id, // Reference to the account
      Geographic_Job_Location__c = 'Ames, IA',
      How_Paid__c = 'Salaried',
      Title__c = 'Salesforce Manager',
      Position_Description__c = 'Manage a great Salesforce team remotely!',
      Position_Link__c = 'https://companyB.com/jobs/2',
      Salary__c = 150000,
      Reported_Last_Updated__c = System.now()
    );
    insert pos2;

    // Create related Job_Application__c record for pos2
    Job_Application__c jobApp = new Job_Application__c(
      Position__c = pos2.Id,
      Company__c = testAccount.Id, // Reference to the account
      Salary__c = pos2.Salary__c,
      How_Paid__c = pos2.How_Paid__c,
      Job_Description__c = pos2.Position_Description__c,
      Position_Reported_Last_Updated__c = System.now().addDays(-2)
    );
    insert jobApp;
  }

  @isTest
  static void testJobApplicationCreatorBatchIsSuccessful() {
    // Start the test by executing the batch
    Test.startTest();

    // Initialize the batch
    JobApplicationCreatorBatch batch = new JobApplicationCreatorBatch();
    Database.executeBatch(batch);

    Test.stopTest();

    // Verify job apps created
    Account acct = [
      SELECT Id
      FROM Account
      WHERE Name LIKE 'Test %' AND CreatedDate = TODAY
      LIMIT 1
    ];
    List<Job_Application__c> jobApps = [
      SELECT Id, Position__c, Position_Reported_Last_Updated__c, Company__c
      FROM Job_Application__c
      WHERE Company__c = :acct.Id
    ];
    Assert.areEqual(
      2,
      jobApps.size(),
      'Number of jobApps created or updated not as expected'
    );

    // Verify Job_Application__c for pos2
    Job_Application__c updatedJobApp = [
      SELECT
        Id,
        Position__c,
        Company__c,
        Position__r.Reported_Last_Updated__c,
        Position_Reported_Last_Updated__c
      FROM Job_Application__c
      WHERE Position_Title__c LIKE '% Manager'
      LIMIT 1
    ];
    Assert.areEqual(
      updatedJobApp.Position__r.Reported_Last_Updated__c,
      updatedJobApp.Position_Reported_Last_Updated__c,
      'Reported update dates not equal as expected'
    );
  }
  @isTest
  static void testBatchJobNoUpdate() {
    // Test when no Job_Application__c records need updating
    List<Account> newAcctLst = Util_TestDataFactory.createTestAccounts(1, true);
    Account testAccount = newAcctLst[0];

    Position__c pos3 = new Position__c(
      Company__c = testAccount.Id, // Reference to the account
      Geographic_Job_Location__c = 'Boston, MA',
      How_Paid__c = 'Salaried',
      Title__c = 'Salesforce Analyst',
      Position_Link__c = 'https://companyC.com/jobs/3',
      Salary__c = 120000,
      Reported_Last_Updated__c = System.now().addDays(-1)
    );
    insert pos3;
    Test.setCreatedDate(pos3.Id, System.now().addDays(-2));
    Test.startTest();

    JobApplicationCreatorBatch batch = new JobApplicationCreatorBatch();
    Database.executeBatch(batch);

    Test.stopTest();

    List<Job_Application__c> jobApps = [
      SELECT Id, Position__c
      FROM Job_Application__c
      WHERE Position__c = :pos3.Id
    ];
    System.assertEquals(
      0,
      jobApps.size(),
      'Expected result of no update did not occur'
    );
  }
}