JaTrMd/objects/Job_Application__c.object
<CustomObject>
    <description>Custom object for tracking job applications</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>The application&apos;s current status</description>
        <inlineHelpText>The application&apos;s current status</inlineHelpText>
        <label>Application Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job App Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Task_for_Stage_Completed__c.field-meta.xml
<CustomField>
    <fullName>Task_for_Stage_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Task for Stage Completed</label>
    <type>Checkbox</type>
</CustomField>

JaTrMd/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Saved</fullName>
        <default>true</default>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>Applying</fullName>
    </customValue>
    <customValue>
        <fullName>Applied</fullName>
    </customValue>
    <customValue>
        <fullName>Interviewing</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiating</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>The status of the job application</description>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Trigger_Classes/TaskTriggerMethods.cls
/**
 * @description       :
 * @author            : admillican08@gmail.com
 * @group             :
 * @last modified on  : 09-29-2024
 * @last modified by  : admillican08@gmail.com
 **/
public with sharing class TaskTriggerMethods {
  public static final String OBJ_NAME = 'Task';
  public static final String CLS_NAME = 'TaskTriggerMethods';

  // used for afterInsert
  public String setTaskForStageCompletedToFalseOnParent(
    Map<Id, Task> newTaskMap
  ) {
    final String MTH_NAME = 'setTaskForStageCompletedToFalseToParent';
    List<Job_Application__c> jobAppsToUpd = new List<Job_Application__c>();
    Set<Id> jobAppIdSet = new Set<Id>();
    for (Id taskId : newTaskMap.keySet()) {
      Task newTask = newTaskMap.get(taskId);
      if (
        newTask.Subject.startsWith('To-Dos') &&
        newTask.Subject.contains('Status') &&
        newTask.Status.equals('Not Started')
      ) {
        jobAppIdSet.add(newTask.WhatId);
      }
    }
    jobAppsToUpd = [
      SELECT Id, Task_for_Stage_Completed__c
      FROM Job_Application__c
      WHERE Id IN :jobAppIdSet AND Application_Status__c != 'Closed'
      WITH USER_MODE
    ];
    for (Job_Application__c jobApp : jobAppsToUpd) {
      jobApp.Task_for_Stage_Completed__c = false;
    }
    return Util_Upsert.upsertList(
      'Job Application',
      jobAppsToUpd,
      MTH_NAME + ' of ' + CLS_NAME
    );
  }

  // used for afterUpdate
  public String setTaskForStageCompletedToTrueOnParent(
    Map<Id, Task> oldTaskMap,
    Map<Id, Task> newTaskMap
  ) {
    final String MTH_NAME = 'setTaskForStageCompletedToTrueOnParent';
    List<Job_Application__c> jobAppsToUpd = new List<Job_Application__c>();
    Set<Id> jobAppIdSet = new Set<Id>();
    for (Id taskId : newTaskMap.keySet()) {
      Task oldTask = oldTaskMap.get(taskId);
      Task newTask = newTaskMap.get(taskId);
      if (
        !oldTask.Status.equals(newTask.Status) &&
        newTask.Subject.startsWith('To-Dos') &&
        newTask.Subject.contains('Status') &&
        !oldTask.Status.equals('Completed') &&
        newTask.Status.equals('Completed')
      ) {
        jobAppIdSet.add(newTask.WhatId);
      }
    }
    jobAppsToUpd = [
      SELECT Id, Task_for_Stage_Completed__c
      FROM Job_Application__c
      WHERE Id IN :jobAppIdSet AND Application_Status__c != 'Closed'
      WITH USER_MODE
    ];
    for (Job_Application__c jobApp : jobAppsToUpd) {
      jobApp.Task_for_Stage_Completed__c = true;
    }
    return Util_Upsert.upsertList(
      'Job Application',
      jobAppsToUpd,
      MTH_NAME + ' of ' + CLS_NAME
    );
  }
}