JaTrMd/objects/Job_Application__c.object
<CustomObject>
    <description>Custom object for tracking job applications</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>The application&apos;s current status</description>
        <inlineHelpText>The application&apos;s current status</inlineHelpText>
        <label>Application Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>The position for which the job application is being submitted</description>
        <inlineHelpText>The position for which the job application is being submitted</inlineHelpText>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job App Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Closed_by_Automated_Process__c.field-meta.xml
<CustomField>
    <fullName>Closed_by_Automated_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The indicator that the application was closed by an automated process</description>
    <inlineHelpText>The indicator that the application was closed by an automated process</inlineHelpText>
    <label>Closed by Automated Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <description>The date on which to follow-up on the job application in some manner; for example, to contact the main point of contact</description>
    <inlineHelpText>The date on which to follow-up on the job application in some manner; for example, to contact the main point of contact</inlineHelpText>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Status__c.field-meta.xml
<CustomField>
    <fullName>Position_Status__c</fullName>
    <description>The status of the position, indicating if it is open or filled</description>
    <formula>TEXT(Position__r.Position_Status__c)</formula>
    <inlineHelpText>The status of the position, indicating if it is open or filled</inlineHelpText>
    <label>Position Status</label>
    <type>Text</type>
</CustomField>

JaTrMd/objects/Position__c.object
<CustomObject>
    <description>The position for which a company is trying to hire an applicant</description>
    <fields>
        <fullName>Position_Status__c</fullName>
        <description>The indicator of whether the position is open for hiring or filled</description>
        <inlineHelpText>The indicator of whether the position is open for hiring or filled</inlineHelpText>
        <label>Position Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Filled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>PSN-{00000}</displayFormat>
        <label>Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JaTrMd/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Saved</fullName>
        <default>true</default>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>Applying</fullName>
    </customValue>
    <customValue>
        <fullName>Applied</fullName>
    </customValue>
    <customValue>
        <fullName>Interviewing</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiating</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <description>The status of the job application</description>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Batch_Sched_Classes/JobApplicationCloserBatch.cls
/**
 * @description       :
 * @author            : admillican08@gmail.com
 * @group             :
 * @last modified on  : 09-26-2024
 * @last modified by  : admillican08@gmail.com
 **/

public with sharing class JobApplicationCloserBatch implements Database.Batchable<sObject> {
  public static final String OBJ_NAME = 'Job Application';
  public static final String CLS_NAME = 'JobApplicationCloserBatch';

  public Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      'SELECT Id, Position__r.Position_Status__c, Application_Status__c, Closed_by_Automated_Process__c, Follow_up_Date__c FROM Job_Application__c WHERE Follow-up_Date__c < LAST_N_DAYS:30 OR Position__r.Position_Status__c = \'Filled\' OR NOT(Application_Status__c = \'Accepted\' OR Application_Status__c = \'Closed\')'
    );
  }

  public void execute(
    Database.BatchableContext bc,
    List<Job_Application__c> scope
  ) {
    final String MTD_NAME = 'execute';
    for (Job_Application__c jobApp : scope) {
      jobApp.Application_Status__c = 'Closed';
      jobApp.Closed_by_Automated_Process__c = true;
    }

    System.debug(
      Util_Upsert.upsertList(OBJ_NAME, scope, MTD_NAME + ' of ' + CLS_NAME)
    );
  }

  public void finish(Database.BatchableContext bc) {
  }
}