JaTrMd/objects/Position__c.object
<CustomObject>
    <description>The position for which a company is trying to hire an applicant</description>
    <fields>
        <fullName>Company__c</fullName>
        <description>The company for which the position is open</description>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position_Status__c</fullName>
        <description>The indicator of whether the position is open for hiring or filled</description>
        <inlineHelpText>The indicator of whether the position is open for hiring or filled</inlineHelpText>
        <label>Position Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Filled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The title of the position</description>
        <inlineHelpText>The title of the position</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>PSN-{00000}</displayFormat>
        <label>Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/External_System_Id__c.field-meta.xml
<CustomField>
    <fullName>External_System_Id__c</fullName>
    <description>Unique Id for external data system</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Id for external data system</inlineHelpText>
    <label>External System Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position__c/fields/Geographic_Job_Location__c.field-meta.xml
<CustomField>
    <fullName>Geographic_Job_Location__c</fullName>
    <description>The geographic location where the jobsite is located</description>
    <inlineHelpText>The geographic location where the jobsite is located</inlineHelpText>
    <label>Geographic Job Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/How_Paid__c.field-meta.xml
<CustomField>
    <fullName>How_Paid__c</fullName>
    <description>How the person with this position will be paid</description>
    <inlineHelpText>How the person with this position will be paid</inlineHelpText>
    <label>How Paid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>How_Paid</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Reported_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>Reported_Last_Updated__c</fullName>
    <description>The reported last updated date and time of the position (as opposed to the Salesforce audit field Last Modified Date)</description>
    <inlineHelpText>The reported last updated date and time of the position (as opposed to the Salesforce audit field Last Modified Date)</inlineHelpText>
    <label>Reported Last Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>The value of the salary allowed for the position</description>
    <inlineHelpText>The value of the salary allowed for the position</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Batch_Sched_Classes/JobApplicationCreatorBatchSchedulerTest.cls
/**
 * @description       : 
 * @author            : admillican08@gmail.com
 * @group             : 
 * @last modified on  : 10-09-2024
 * @last modified by  : admillican08@gmail.com
**/
@isTest
public class JobApplicationCreatorBatchSchedulerTest {
  @TestSetup
  private static void makeData() {
        List<Account> acctLst = Util_TestDataFactory.createTestAccounts(1, TRUE); 
        Account acct = acctLst[0];
    Position__c newPos1 = new Position__c(
      Company__c = acct.Id,
      External_System_Id__c = '24420974192',
      Geographic_Job_Location__c = 'Richardson, TX',
      How_Paid__c = 'Salaried Annually',
      Position_Status__c = 'Open',
      Reported_Last_Updated__c = System.now(),
      Title__c = 'Salesforce Architect',
      Salary__c = 220000
    );
    insert newPos1;
    }
  

    @isTest
    static void testSchedulerExecution() {
      Test.startTest();
      Position__c posn = [SELECT Id FROM Position__c WHERE External_System_Id__c = '24420974192' LIMIT 1];
      Assert.IsNotNull(posn.Id, 'Matching position not found as expected');
      JobApplicationCreatorBatchScheduler scheduler = new JobApplicationCreatorBatchScheduler();
    
        String jobId = System.schedule('Test JobApplicationCreatorBatchScheduler', '0 0 0 15 10 ? 2024', scheduler);
      
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
      Test.stopTest();
        // Validate the job is scheduled correctly
        Assert.areEqual('0 0 0 15 10 ? 2024', ct.CronExpression, 'Cron expression not equal to supplied param as expected');
    }


}