JaTrMd/objects/Trigger_Setting__mdt.object
<CustomObject>
    <description>Allows for the suspension of trigger operations</description>
    <fields>
        <fullName>Trigger_Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The indicator that the trigger is disabled if selected</description>
        <inlineHelpText>The indicator that the trigger is disabled if selected</inlineHelpText>
        <label>Trigger Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sObject__c</fullName>
        <description>The sObject affected by the trigger</description>
        <inlineHelpText>The sObject affected by the trigger</inlineHelpText>
        <label>sObject</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Job_Application__c</fullName>
                </value>
                <value>
                    <fullName>Job_Application_Note__c</fullName>
                </value>
                <value>
                    <fullName>OpportunityLineItem</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Position__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trigger Setting</label>
    <pluralLabel>Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/Trigger_Classes/TriggerHandler.cls
/**
 * @description       :
 * @author            : admillican08@gmail.com
 * @group             :
 * @last modified on  : 09-12-2024
 * @last modified by  : admillican08@gmail.com
 **/
public with sharing virtual class TriggerHandler {
  public static boolean isDisabled { get; private set; }
  public static boolean isExempt { get; private set; }

  public TriggerHandler(String sObjName) {
    List<Trigger_Setting__mdt> trigSet = [
      SELECT Id, sObject__c, Trigger_Disabled__c
      FROM Trigger_Setting__mdt
      WHERE sObject__c = :sObjName
      WITH SYSTEM_MODE
    ];
    isDisabled = trigSet.isEmpty() ? false : trigSet[0].Trigger_Disabled__c;
    isExempt = FeatureManagement.checkPermission('Trigger_Exempt');
  }

  public static Boolean setIsDisabled(Boolean isDsbld) {
    isDisabled = isDsbld;
    return isDisabled;
  }
}