force-app/main/default/objects/Tax_Bracket__mdt/Tax_Bracket__mdt.object-meta.xml
<CustomObject>
    <description>For variables related to the salary calculator</description>
    <label>Tax Bracket</label>
    <pluralLabel>Tax Brackets</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tax_Bracket__mdt/fields/Ending_Salary__c.field-meta.xml
<CustomField>
    <fullName>Ending_Salary__c</fullName>
    <label>Ending Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Bracket__mdt/fields/Starting_Salary__c.field-meta.xml
<CustomField>
    <fullName>Starting_Salary__c</fullName>
    <label>Starting Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Bracket__mdt/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <default>true</default>
                <label>10</label>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>37</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Controller_Classes/TaxMetadataController.cls
/**
 * @description       :
 * @author            : admillican08@gmail.com
 * @group             :
 * @last modified on  : 09-19-2024
 * @last modified by  : admillican08@gmail.com
 **/
public with sharing class TaxMetadataController {
  public static Map<String, Tax_Bracket__mdt> taxBracketMap {
    get {
      if (taxBracketMap == null) {
        taxBracketMap = new Map<String, Tax_Bracket__mdt>();
        taxBracketMap = Tax_Bracket__mdt.getAll();
      }
      return taxBracketMap;
    }
    set;
  }

  @AuraEnabled(cacheable=true)
  public static Decimal getTaxRatePercentage(
    String filingStatusVal,
    Decimal salAmt,
    Integer currYr
  ) {
    Decimal taxBr = 0.00;
    List<Tax_Bracket__mdt> taxBracketVals = taxBracketMap.values();
    for (Tax_Bracket__mdt taxBracket : taxBracketVals) {
      if (
        filingStatusVal != null &&
        salAmt != null &&
        currYr != null &&
        taxBracket.DeveloperName.startsWith(filingStatusVal) &&
        (Decimal) (taxBracket.Starting_Salary__c) <= salAmt &&
        (taxBracket.Ending_Salary__c == 0 ||
        (Decimal) (taxBracket.Ending_Salary__c) >= salAmt) &&
        taxBracket.Year_Valid__c == currYr
      ) {
        System.debug('**Found match on ' + taxBracket.developername);
        return Decimal.valueOf(taxBracket.Tax_Rate__c);
      }
    }
    System.debug('**Returning 0.00 tax rate');
    return taxBr;
  }
}